try {		
	console.log( "something..." );	
} 
catch( e ) 
{
	console.log( "exception: " + e );
	throw( e );
}


