try {		
	console.log( "Not matter any more\n" );	
} 
catch( e ) 
{
	console.log( "exception: " + e );
	throw( e );
}


